In [38]:
from IPython.display import display
import os
os.getcwd()

'C:\\Users\\ikki_ikazaki\\KIBIT\\analysis_with_kibit_180131'

In [4]:
import pandas as pd

sample = pd.read_csv('data\\sample.csv', engine='python')
sample

ID  フラグ（苦情）  フラグ（感謝）  フラグ（意見要望）  \
0      1        0        0          0   
1      2        0        0          0   
2      3        0        0          1   
3      4        0        0          0   
4      5        0        0          0   
5      6        0        0          0   
6      7        0        0          0   
7      8        0        0          0   
8      9        0        0          0   
9     10        0        0          0   
10    11        0        0          0   
11    12        0        0          0   
12    13        0        0          0   
13    14        0        0          1   
14    15        0        0          0   
15    16        0        0          0   
16    17        0        0          0   
17    18        0        0          0   
18    19        0        0          0   
19    20        0        0          0   
20    21        0        0          0   
21    22        0        0          0   
22    23        0        0          0   
23    24        0        0          0   
24    25        0        0          0   
25    26        0        0          0   
26    27        0        0          0   
27    28        0        0          0   
28    29        0        0          0   
29    30        0        0          0   
..   ...      ...      ...        ...   
518  519        0        0          0   
519  520        0        0          0   
520  521        0        0          0   
521  522        0        0          0   
522  523        0        0          0   
523  524        0        0          0   
524  525        0        0          0   
525  526        0        0          0   
526  527        0        0          0   
527  528        0        0          0   
528  529        0        0          0   
529  530        0        0          0   
530  531        0        0          0   
531  532        0        0          1   
532  533        0        0          0   
533  534        0        0          0   
534  535        0        0          0   
535  536        0        0          0   
536  537        0        0          0   
537  538        0        0          0   
538  539        0        0          0   
539  540        0        0          0   
540  541        0        0          0   
541  542        0        0          0   
542  543        0        0          0   
543  544        0        0          0   
544  545        0        0          0   
545  546        0        0          0   
546  547        1        0          0   
547  548        0        0          0   

                                                  text  HOT  NOT  test  
0    \n先日、貴店にてポイントカードのご紹介を頂きましたが、何回登録にトライしても登録が完了でき...    0    1     0  
1    \nポイントカードについての質問です。パスワードを忘れた為登録していたメールアドレスに返信依...    0    1     0  
2    \nポイントカードのパスワードを紛失し、登録のメールアドレスももう使用していないため、パスワ...    0    1     0  
3    \nかなり前、ポイントカードの登録を行いましたが、オンラインにて購入しようと思ったところID...    0    1     0  
4    \nポイントカードの登録がうまくいきません。\nメールアドレスがもう登録されていますになるの...    0    1     0  
5    \nいつもお世話になっております。\n会員専用webサイトにログインでません。\nパスワード...    0    1     0  
6    \nポイントカードはもっているのですが、携帯から登録しようとしたところパスワードを忘れてしま...    0    1     0  
7    \n新しいパスワードに変更したく、ログインしたいのですが、最初に登録したパスワードを思い出せ...    0    1     0  
8    \nポイントカードを紛失したため、本日（12/26）再発行をお願いしました。\n再度登録を、...    0    1     0  
9    \nポイントカードの会員ログインを使用としたところ、ログインできませんでした。パスワードが違...    0    1     0  
10   \nポイントカードについて問い合わせいたします。\nログインしようとしたのですが、パスワード...    0    1     0  
11   \n携帯のアドレスを変更したため、ポイントカードのメールアドレスを再登録しようとしましたが、...    0    1     0  
12   \nポイントカードの登録メールアドレスを変更したいのですが、\n・登録パスワードを忘れた\n...    0    1     0  
13   \nカードを使用しないので、個人情報を削除し、退会したいのですが、手続きを行う前に登録してい...    0    1     0  
14   \n担当さま\n本日11/24、●●●店で購入した際、ポイントカードをいただき、帰宅後web...    0    1     0  
15   \n失礼致します。\nメールアドレスを変更してしまいログインができないため、\nID及びパス...    0    1     0  
16   お世話になっております。\n\nポイントカードについてご相談があります。\n\n現在、ポイン...    0    1     0  
17   \nパスワードが分からず、また以前登録したメールアドレスからも変更しているので、ログインや問...    0    1     0  
18   \nメールアドレスが変わったので変更したいが、パスワードを忘れてログインできない。パスワード...    0    1     0  
19 

In [16]:
import numpy as np

test = list(sample[sample['test'] == 1].index)
test

[544, 545, 546, 547]

In [51]:
sample.sort_values(by='test', ascending=False)
test = sample.iloc[544:548, :]
test

ID  フラグ（苦情）  フラグ（感謝）  フラグ（意見要望）  \
544  545        0        0          0   
545  546        0        0          0   
546  547        1        0          0   
547  548        0        0          0   

                                                  text  HOT  NOT  test  
544    \n●●●\n2男性モデル着用のコートは何色でしょうか。\n年齢：\nポイントカード：\n\n    0    1     1  
545  \n2初めて●●●で買いました。ポイントカードを貰いまして会員登録をしましたら突然ID番号を...    0    1     1  
546  \n2先日●●●さんで買い物をした●●●と申します。\nあまり言いたくはないですが、クレーム...    1    0     1  
547                                                NaN    0    0     1

In [53]:
test.to_csv('data\\test.csv', encoding='utf-8-sig')

### NumPy Basics: Arrays and

In [2]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [3]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 40 ms
Wall time: 1.57 s


### The NumPy ndarray: A Multidimensional Array Object

In [9]:
import numpy as np
# Generate some random data
data = np.random.randn(2, 3)
data

array([[ 1.669 , -0.4386, -0.5397],
       [ 0.477 ,  3.2489, -1.0212]])

In [11]:
# ベクトル演算
# ndarrayは、各要素を計算するときにfor文を書く必要がない。一括で計算してくれる。
data * 10

array([[ 16.6903,  -4.3857,  -5.3974],
       [  4.7699,  32.4894, -10.2123]])

In [12]:
data + data

array([[ 3.3381, -0.8771, -1.0795],
       [ 0.954 ,  6.4979, -2.0425]])

In [15]:
# 配列次元数とそのサイズを格納するタプル
data.shape

(2, 3)

In [16]:
# 配列要素に期待する型を示す
data.dtype

dtype('float64')

### Creating ndarrays

In [17]:
# リストを作ってndarrayにする。
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [18]:
# リストをネストさせることで、行列を作れる。
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
# ndarrayの作り方1
print(np.zeros(10))
print(np.ones(10))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [29]:
# ndarrayの作り方2
# 生成するndarrayのshapeを第一引数に渡す。
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [31]:
# ndarrayの作り方3
# 生成するndarrayのshapeを第一引数に渡す。
np.empty((2, 3, 2))

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [32]:
# 等間隔に増減させた値で要素を満たす
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Basic Indexing and Slicing

In [39]:
# スライスが使える。
arr = np.arange(10)
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [40]:
# スライスが使える。
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [41]:
# スライスを格納した変数に対する変更は、もとのndarrayにも反映される。
arr_slice[0] = 12345
arr

array([    0,     1,     2,     3,     4, 12345,    12,    12,     8,     9])

In [49]:
# 2次元配列のインデックス
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('2次元配列に対して、インデックスを1つ指定した場合、該当行を返す;', arr2d[2])
print('2次元配列に対して、列を指定する場合、次のように[行,列]を書く。', arr2d[:,2])

# 下記2つの書き方は同じ場所を参照できる。
print(arr2d[0][2])
print(arr2d[0, 2])

2次元配列に対して、インデックスを1つ指定した場合、該当行を返す; [7 8 9]
[3 6 9]
3
3


3